import { INDENT } from './constants'

const escapeKey = (key: string) => key.replace(/\\/g, '\\\\').replace(/'/g, '\\\'')

const formatActions = (actions: string[]) => {
  if (!actions.length) {
    return `${INDENT.repeat(2)}[action: string]: boolean`
  }

  return actions
    .map(action => `${INDENT.repeat(2)}'${escapeKey(action)}': boolean`)
    .join('\n')
}

const buildPermissionTree = (permissions: Record<string, string[]>) => {
  const entries = Object.entries(permissions)
  if (!entries.length) {
    return `any`
  }

  const body = entries
    .map(([resource, actions]) => [
      `${INDENT}'${escapeKey(resource)}': {`,
      formatActions(actions),
      `${INDENT}}`,
    ].join('\n'))
    .join('\n')

  return `{
${body}
}`
}

export const generateTypeDeclaration = (permissions: Record<string, string[]>) => {
  const permissionTree = buildPermissionTree(permissions)

  return `/* eslint-disable */
// Generated by nuxt-can – do not edit manually.
type NuxtCanChecker = (path: string[]) => boolean | Promise<boolean>
type NuxtCanPermissions = ${permissionTree}

declare module 'vue' {
${INDENT}interface ComponentCustomProperties {
${INDENT.repeat(2)}can: NuxtCanPermissions
${INDENT.repeat(2)}$can: NuxtCanPermissions
${INDENT.repeat(2)}__can__: NuxtCanChecker
${INDENT}}
}

declare module '#app' {
${INDENT}interface NuxtApp {
${INDENT.repeat(2)}$can: NuxtCanPermissions
${INDENT.repeat(2)}$__can__: NuxtCanChecker
${INDENT}}
}

export {}
`
}
